---
title: "Visualizing Workflow Output"
params:
  store: !r file.path("..","_targets")
output:
  html_notebook:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: yes
    toc_depth: 4
---

# loading the packages

```{r setup}
library(targets)

library(knitr)

library(tidyverse)

library(Radviz)

theme_set(theme_light(base_size = 16))
tar_config_set(store = params$store)
```

# loading the data

```{r data}
tar_load(markers)
tar_load(annots)
tar_load(live.df)
tar_load(live.mem.plot)
tar_load(live.hilbert.proj)
tar_load(live.hilbert.dist)
tar_load(pheno.rv)
tar_load(func.rv)
```

# Channel Overview

```{r,fig.width=12,fig.height=9}
live.df %>%
    dplyr::select(all_of(c("name",
                    with(markers,
                         name[type %in% c("phenotypic",
                                          "functional")])))) %>% 
    rename_with(~ with(markers,
                       desc[match(.x,name)]),
                !name) %>% 
    left_join(annots,
              by = "name") %>% 
    sample_frac(0.1) %>% 
    gather(Channel, value,
           all_of(with(markers,
                       desc[type %in% c("phenotypic",
                                        "functional")]))) %>% 
    mutate(Channel = factor(Channel,
                            levels = c(rownames(springs(pheno.rv)),
                                       rownames(springs(func.rv))))) %>% 
    ggplot(aes(x = value))+
    geom_density()+
    geom_vline(data = . %>% 
                   group_by(Channel) %>% 
                   reframe(value = quantile(value,c(0,0.99))),
               aes(xintercept = value),
               col = 2)+
    facet_wrap(~Channel,
               scales = "free_y")+
    xlim(0,NA)
```

# MEM results {.tabset}

## Batch

```{r}
live.mem.plot+
    geom_point(aes(color = BatchId),
               size = 3)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Treatment

```{r}
live.mem.plot+
    geom_point(aes(color = Timepoint),
               size = 3)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Patient Type

```{r}
live.mem.plot+
    geom_point(aes(color = PatientType),
               size = 3)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## HD vs Patient at Baseline

```{r}
live.mem.plot+
    geom_point(data = . %>% 
                   filter(Timepoint=="baseline"),
               aes(color = PatientType),
               size = 3)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
live.mem.plot+
    geom_point(aes(color = PatientType),
               size = 3)+
    facet_grid(rows = vars(Timepoint))+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
## Where is Patient #1?

```{r}
live.mem.plot+
    geom_point(data = . %>% 
                   mutate(isPT1 = Individual=="PT1" & 
                              Timepoint=="treated") %>% 
                   arrange(isPT1),
               aes(color = isPT1),
               size = 3)+
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

# HilbertSimilarity

```{r, fig.height = 12}
plot(hclust(live.hilbert.dist))
```

```{r}
hc <- hclust(live.hilbert.dist)
hc$labels <- with(annots,Individual[match(name,hc$labels)])
plot(hc)
```


# Radviz {.tabset}

## Phenotypic

```{r, fig.width=9}
plot(pheno.rv)+
    geom_density2d(data = . %>% 
                       group_by(name) %>% 
                       sample_frac(0.1),
                   aes(color = Timepoint))+
    facet_grid(cols = vars(PatientType))
```

## Functional

```{r, fig.width=9}
plot(func.rv)+
    geom_density2d(data = . %>% 
                       group_by(name) %>% 
                       sample_frac(0.1),
                   aes(color = Timepoint))+
    facet_grid(cols = vars(PatientType))
```

## Functional

```{r}
plot(func.rv)+
    geom_density2d(data = . %>% 
                       group_by(name) %>% 
                       sample_frac(0.1) %>% 
                       unite("Condition",
                             PatientType,Timepoint),
                   aes(color = Condition))
```
